In [1]:
# Import necessary packages
from __future__ import print_function
import os
import sys
import cv2
import numpy as np

In [2]:
#running function to understand the working directory which should be easy but isn't
import os
cwd = os.getcwd()
print(cwd)

/Users/masterambassador/Slitherin/Celeb Images


In [3]:
#make file alias to make my life easier
imgdr = "/Users/masterambassador/Slitherin/Celeb Images/cimages"

In [4]:
#This function counts the number of pictures in the directory
numImages = len(imgdr)
print(numImages)

54


In [9]:
#This function ensures directory isn't empty
import csv
img=os.path.join("cimages","00001.jpg")
print(img)

cimages/00001.jpg


In [ ]:
#this function calculates size of each image
#all images in file are same size 178x218 pixels
img.size

In [11]:
#Python needs PIL-Image library to view images 
from PIL import Image
imgdr = '/Users/masterambassador/Slitherin/Celeb Images/cimages'

In [29]:
#Eigen step 1 -Run this piece of code first in the series after testing your dependencies and files
# Read images from the directory - THIS IS A FUNCTION HE REFERENCES LATER
print("Reading images from " + imgdr, end="...")
# Create array of array of images.
images = []
# List all files in the directory and read points from text files one by one
for filePath in sorted(os.listdir(imgdr)):
    fileExt = os.path.splitext(filePath)[1]
    print(fileExt)
    print(filePath)
    if fileExt in [".jpg", ".jpeg"]:

        # Add to array of images
        imagePath = os.path.join(imgdr, filePath)
        im = cv2.imread(imagePath) #This is how OpenCV opens image files
        print(im)

        if im is None :
            print("image:{} not read properly".format(imagePath))
        else :

            # Convert image to floating point
            im = np.float32(im)/255.0
            images.append(im) # Add image to list
            imFlip = cv2.flip(im, 1);# Flip image 
            images.append(imFlip)# Append flipped image to dictionary
        
numImages = int(len(images) / 2) #Divide by 2 because OpenCV forbids negative numbers in sliders
if numImages == 0 : # Exit if no image found
            print("No images found")
            sys.exit(0)
print(str(numImages) + " files read.")

Reading images from /Users/masterambassador/Slitherin/Celeb Images/cimages....jpg
000001.jpg
[[[194 231 253]
  [194 231 253]
  [194 231 253]
  ...
  [216 228 246]
  [223 237 255]
  [222 238 254]]

 [[194 231 253]
  [194 231 253]
  [194 231 253]
  ...
  [218 230 248]
  [223 237 255]
  [222 238 254]]

 [[194 231 253]
  [194 231 253]
  [194 231 253]
  ...
  [220 232 250]
  [224 238 255]
  [223 239 255]]

 ...

 [[ 26  74 140]
  [  1  49 115]
  [ 33  78 146]
  ...
  [ 28  55 122]
  [ 30  56 123]
  [ 30  56 122]]

 [[ 15  62 130]
  [ 23  70 138]
  [ 53  98 166]
  ...
  [ 20  49 118]
  [ 24  50 120]
  [ 24  51 118]]

 [[ 53 100 168]
  [ 89 136 204]
  [132 177 245]
  ...
  [ 20  49 118]
  [ 24  50 120]
  [ 24  50 120]]]
.jpg
000002.jpg
[[[ 45  52  67]
  [ 43  50  65]
  [ 43  50  65]
  ...
  [ 68  73  76]
  [ 74  79  82]
  [ 74  81  84]]

 [[ 45  52  67]
  [ 43  50  65]
  [ 43  50  65]
  ...
  [ 68  73  76]
  [ 74  79  82]
  [ 74  81  84]]

 [[ 47  52  67]
  [ 45  50  65]
  [ 43  50  65]
  ...

In [ ]:
return images # not images anymore now a numerical matrix representing images

In [ ]:
import os
import cv2
import sys
import shutil
import random
import numpy as np

In [17]:
# Directory containing images
dirName = "/Users/masterambassador/Slitherin/Celeb Images/cimages"

In [20]:
len(imgdr)

54

In [28]:
#%%
# Create data matrix from a list of images
def createDataMatrix(images):
    print("Creating data matrix",end=" ... ")
    numImages = len(images)
    sz = images[0].shape
    data = np.zeros((numImages, sz[0] * sz[1] * sz[2]), dtype=np.float32)
    for i in range(0, numImages):
        image = images[i].flatten()
        data[i,:] = image
    print("DONE")
    #return data
    #print(data)
    
#Allocate space for all images in one data matrix.
#The size of the data matrix is
#( w  * h  * 3, numImages )
#where,
#w = width of an image in the data set.
#h = height of an image in the data set.
#3 is for the 3 color channels.
#'''




In [16]:
# #Eigen step 2
#this is how the interpreter notes that this is to be run first is the main code
if __name__ == '__main__': 

    # Number of EigenFaces
    NUM_EIGEN_FACES = 10

    # Maximum weight
    MAX_SLIDER_VALUE = 255

    # Read images
    images = readImages(dirName)
    print(images)
    # Size of images
    sz = images[0].shape

    # Create data matrix for PCA.
    data = createDataMatrix(images)

NameError: name 'readImages' is not defined

In [ ]:
def resetSliderValues(*args):
    for i in range(0, NUM_EIGEN_FACES):
        cv2.setTrackbarPos("Weight" + str(i), "Trackbars", int(MAX_SLIDER_VALUE/2));
    createNewFace()

In [13]:
# Add the weighted eigen faces to the mean face 
#openCV has unresolved bug, NULL POINTER had to downgrade to 3.4

def createNewFace(*args):

# Start with the mean image
    output = averageFace

# Add the eigen faces with the weights
#'''OpenCV does not allow slider values to be negative. 
#So we use weight = sliderValue - MAX_SLIDER_VALUE / 2
#''' 
for i in range(0, NUM_EIGEN_FACES):
        sliderValues[i] = cv2.getTrackbarPos("Weight" + str(i), "Trackbars");
        weight = sliderValues[i] - MAX_SLIDER_VALUE/2
        output = np.add(output, eigenFaces[i] * weight)

# Display Result at 2x size
output = cv2.resize(output, (0,0), fx=2, fy=2)
cv2.imshow("Result", output)

NameError: name 'NUM_EIGEN_FACES' is not defined

In [44]:
print((os.listdir(imgdr)))

['000004.jpg', '000005.jpg', '000001.jpg', '000002.jpg', '000003.jpg']


In [ ]:
print(file)

In [46]:
len(images)

2

In [77]:

#%%
numImages = len(images)
sz = images[0].shape
data = np.zeros((numImages, sz[0] * sz[1] * sz[2]), dtype=np.float32)
for i in range(0, numImages):
    image = images[i].flatten()
    data[i,:] = image

print("DONE")
#return data
print(data)



DONE
[[0.7607843  0.90588236 0.99215686 ... 0.09411765 0.19607843 0.47058824]
 [0.87058824 0.93333334 0.99607843 ... 0.20784314 0.39215687 0.65882355]
 [0.1764706  0.20392157 0.2627451  ... 0.4392157  0.46666667 0.54509807]
 ...
 [0.04313726 0.02352941 0.02745098 ... 0.48235294 0.49803922 0.5176471 ]
 [0.79607844 0.77254903 0.59607846 ... 0.7921569  0.78039217 0.5803922 ]
 [0.78431374 0.7921569  0.5568628  ... 0.7882353  0.78039217 0.5686275 ]]


In [79]:
print(images)

[array([[[0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        ...,
        [0.84705883, 0.89411765, 0.9647059 ],
        [0.8745098 , 0.92941177, 1.        ],
        [0.87058824, 0.93333334, 0.99607843]],

       [[0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        ...,
        [0.85490197, 0.9019608 , 0.972549  ],
        [0.8745098 , 0.92941177, 1.        ],
        [0.87058824, 0.93333334, 0.99607843]],

       [[0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        [0.7607843 , 0.90588236, 0.99215686],
        ...,
        [0.8627451 , 0.9098039 , 0.98039216],
        [0.8784314 , 0.93333334, 1.        ],
        [0.8745098 , 0.9372549 , 1.        ]],

       ...,

       [[0.10196079, 0.2901961 , 0.54901963],
        [0.00392157, 0.19215687, 0.4509804 ],
        [0.12941177, 

In [64]:
print(createDataMatrix(images))

Creating data matrix ... 

TypeError: object of type 'NoneType' has no len()

In [4]:
print(numImages)

54


In [21]:
with open(file1,newline="") as filereader:
    filehandler=csv.DictReader(filereader,delimiter=',')
    print(filehandler)

In [ ]:
print(images1)

In [71]:
print(images)

None


In [ ]:
	# Compute the eigenvectors from the stack of images created
	print("Calculating PCA ", end="...")
	mean, eigenVectors = cv2.PCACompute(data, mean=None, maxComponents=NUM_EIGEN_FACES)
	print ("DONE")

In [ ]:
	averageFace = mean.reshape(sz)

	eigenFaces = []; 

	for eigenVector in eigenVectors:
		eigenFace = eigenVector.reshape(sz)
		eigenFaces.append(eigenFace)

	# Create window for displaying Mean Face
	cv2.namedWindow("Result", cv2.WINDOW_AUTOSIZE)
	
	# Display result at 2x size
	output = cv2.resize(averageFace, (0,0), fx=2, fy=2)
	cv2.imshow("Result", output)

In [6]:
	# Create Window for trackbars
	cv2.namedWindow("Trackbars", cv2.WINDOW_AUTOSIZE)

	sliderValues = []
	
	# Create Trackbars
	for i in range(0, NUM_EIGEN_FACES):
		sliderValues.append(int(MAX_SLIDER_VALUE/2))
		cv2.createTrackbar( "Weight" + str(i), "Trackbars", int(MAX_SLIDER_VALUE/2), MAX_SLIDER_VALUE, createNewFace)
	
	# You can reset the sliders by clicking on the mean image.
	cv2.setMouseCallback("Result", resetSliderValues);
	
	print('''Usage:
	Change the weights using the sliders
	Click on the result window to reset sliders
	Hit ESC to terminate program.''')

	cv2.waitKey(0)
cv2.destroyAllWindows()

NameError: name 'createNewFace' is not defined

In [4]:
#%%THE WRONG ONE
# Create data matrix from a list of images
def createDataMatrix(images):
    print("Creating data matrix",end=" ... ")
#''' 
#Allocate space for all images in one data matrix.
#The size of the data matrix is
#( w  * h  * 3, numImages )
#where,
#w = width of an image in the data set.
#h = height of an image in the data set.
#3 is for the 3 color channels.
#'''


#%%
numImages = len("/Users/masterambassador/Slitherin/Celeb Images/cimages")
sz = "/Users/masterambassador/Slitherin/Celeb Images/cimages"[0].shape
data = np.zeros((numImages, sz[0] * sz[1] * sz[2]), dtype=np.float32)
for i in range(0, numImages):
    image = images[i].flatten()
    data[i,:] = image

print("DONE")
return data


#1 order
# Read images from the directory - THIS IS A FUNCTION HE REFERENCES LATER
#def readImages("/Users/masterambassador/Slitherin/Celeb Images/cimages"):
#	print("Reading images from " + cimages, end="...")
	# Create array of array of images.
	images = []
	# List all files in the directory and read points from text files one by one
	for filePath in sorted(os.listdir(cimages)):
		fileExt = os."/Users/masterambassador/Slitherin/Celeb Images/cimages".splitext(filePath)[1]
		if fileExt in [".jpg", ".jpeg"]:

			# Add to array of images
			imagePath = os.cimages.join(cimages, filePath)
			im = cv2.imread(imagePath) #THIS IS A CV OPEN IM READ

			if im is None :
				print("image:{} not read properly".format(imagePath))
			else :
				# Convert image to floating point
				im = np.float32(im)/255.0
				# Add image to list
				images.append(im)
				# Flip image 
				imFlip = cv2.flip(im, 1);
				# Append flipped image
				images.append(imFlip)
	numImages = int(len(images) / 2)
	# Exit if no image found
	if numImages == 0 :
		print("No images found")
		sys.exit(0)

	print(str(numImages) + " files read.")
	return images


#%%
# Add the weighted eigen faces to the mean face 
def createNewFace(*args):
	# Start with the mean image
	output = averageFace
	
	# Add the eigen faces with the weights
	for i in range(0, NUM_EIGEN_FACES):
		#'''
		#OpenCV does not allow slider values to be negative. 
		#So we use weight = sliderValue - MAX_SLIDER_VALUE / 2
		#''' 
		sliderValues[i] = cv2.getTrackbarPos("Weight" + str(i), "Trackbars");
		weight = sliderValues[i] - MAX_SLIDER_VALUE/2
		output = np.add(output, eigenFaces[i] * weight)

	# Display Result at 2x size
	output = cv2.resize(output, (0,0), fx=2, fy=2)
	cv2.imshow("Result", output)



SyntaxError: invalid syntax (<ipython-input-4-425688588977>, line 17)